# permissions for end users to view promptfooconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: promptfooconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-promptfoo-controller
    app.kubernetes.io/part-of: kube-promptfoo-controller
    app.kubernetes.io/managed-by: kustomize
  name: promptfooconfig-viewer-role
rules:
- apiGroups:
  - promptfoo.promptfoo.x-k8s.io
  resources:
  - promptfooconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - promptfoo.promptfoo.x-k8s.io
  resources:
  - promptfooconfigs/status
  verbs:
  - get
