---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - promptfoo.promptfoo.x-k8s.io
  resources:
  - promptfooconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - promptfoo.promptfoo.x-k8s.io
  resources:
  - promptfooconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - promptfoo.promptfoo.x-k8s.io
  resources:
  - promptfooconfigs/status
  verbs:
  - get
  - patch
  - update
